---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: kubectl config set-cluster
  ansible.builtin.shell: >
    set -o errexit; \
    kubectl config set-cluster {{ k8s_config_cluster_name }} \
      --certificate-authority={{ k8s_ca_conf_directory }}/ca-k8s-apiserver.pem \
      --embed-certs=true \
      --server=https://10.10.10.10:6443
  register: set_cluster
  changed_when: false

- name: kubectl config set-credentials admin
  ansible.builtin.shell: >
    set -o errexit; \
    kubectl config set-credentials admin \
      --client-certificate={{ k8s_ca_conf_directory }}/cert-admin.pem \
      --client-key={{ k8s_ca_conf_directory }}/cert-admin-key.pem
  register: set_credentials
  changed_when: false

- name: kubectl config set-context
  ansible.builtin.shell: >
    set -o errexit; \
    kubectl config set-context {{ k8s_config_cluster_name }} \
      --cluster={{ k8s_config_cluster_name }} \
      --user=admin
  register: set_context
  changed_when: false

- name: kubectl config use-context
  ansible.builtin.shell: >
    set -o errexit; \
    kubectl config use-context {{ k8s_config_cluster_name }}
  register: use_context
  changed_when: false
